### ISSUE TITLE
Hard to set The Admin address

### ISSUE THREAD

**Issue by Bkroland19** [Ayan-Banerjee-918/VoteBlocks-Dapp#2]
Hello Sir, how can i set the admin contract address

**Comment by Ayan-Banerjee-918** [comment]
By setting admin contract address, do you mean to give your account administrator rights?

**Comment by Bkroland19** [comment]
Hello Ayan,

I hope this email finds you well. I'm writing because I'm having trouble
accessing the admin panel. I tried to set the address as directed but it
didn't work. Could you please provide me with some assistance?

Thank you for your help!

Best regards,

Bukenya Kizza

**Comment by Bkroland19** [comment]
i mean from this statement     **_Browse to https://voteblocks.netlify.app/adminApp/adminLogin or localhost:port/adminApp/adminLogin
Note : THIS PAGE IS ACCESSIBLE ONLY IF WALLET ADDRESS IS GIVEN ADMIN RIGHTS_**
what did you mean by  the note part and how do i achieve it

**Comment by Ayan-Banerjee-918** [comment]
In order to give yourself admin rights in the website, use the provided admin details to login into metamask, authenticator , and then the dapp, you will find yourself in the admin panel.....

There you will get option to verify your other registered account, and after verification, you can provide yourself admin role from there.

Once done, you can logout, use your registered account to login, and you will see you have admin access as well.

**Comment by Ayan-Banerjee-918** [comment]
I checked the provided account details , it's logging in fine, let me know exactly where are you facing the issue during admin login, I will help you out!!

**Comment by Bkroland19** [comment]
Dear Ayan Banerjee,

I hope this email finds you well. I wanted to reach out to you regarding
the issue I'm facing with the admin login. When I try to navigate to the
admin route, both on localhost and the hosted version, I'm getting a 404
error. I have checked the provided account details and it seems to be
logging in fine.

Could you please assist me in resolving this issue? I would greatly
appreciate your help.

Thank you in advance!

Best regards,
Bukenya K

**Comment by Ayan-Banerjee-918** [comment]
Try this:
Instead of going directly to the admin route, first go to the main site, i.e, voteblocks.netlify.app , then import into metamask the provided account, after that visit the admin route, i think it will work.

Remember the provided metamask account is of polygon mumbai net, so after importing the acc, do remember to switch the network from ethereum mainnet to polygon mumbai (add it as a custom network )....

**Comment by Bkroland19** [comment]
here is what i get when i try to import the account

**Comment by Bkroland19** [comment]
it can't import that account you provided

**Comment by Ayan-Banerjee-918** [comment]
no image has been attached so unable to check!! And let me know how you are importing the account!

**Comment by Bkroland19** [comment]
i copy the


   - Import account 0x2AAD4FFDefCAB7D7Dd0B8D500a8f70c1A38513e4 into
   Metamask with private key

e439ae6593376e149f0421f7ae7b3c777cc1da5e7d47923766f2e0f85030e723

and went to metamask import(private key) and then pasted in this
e439ae6593376e149f0421f7ae7b3c777cc1da5e7d47923766f2e0f85030e723

**Comment by Ayan-Banerjee-918** [comment]
Yes then?
Kindly attach a screenshot or screen recording regarding what is happening.

**Comment by Bkroland19** [comment]
Then it brings the error i have sent you in the attachment

**Comment by Ayan-Banerjee-918** [comment]
No attachment is visible , kindly respond from github and attach it here

**Comment by Bkroland19** [comment]
https://res.cloudinary.com/itgenius/image/upload/v1684244760/Screenshot_from_2023-05-16_14-55-45_vvptmi.png

thats the link to the image am talking about

**Comment by Bkroland19** [comment]
![Screenshot from 2023-05-16 14-55-45](https://github.com/Ayan-Banerjee-918/VoteBlocks-Dapp/assets/65455750/b6d8b9b6-cdb6-400e-992b-49641b2e3ce8)

**Comment by Ayan-Banerjee-918** [comment]
It seems you are on localhost, can you switch that to polygon mumbai subnet first?

**Comment by Bkroland19** [comment]
oh let me first switch to that  network but i dont know how to switch to it

**Comment by Ayan-Banerjee-918** [comment]
Click on localhost => Add Network => Add a network manually

Fill in the following details:

Network Name: Mumbai Testnet
New RPC URL: https://rpc-mumbai.maticvigil.com/
Chain ID: 80001
Currency Symbol: MATIC
Block Explorer URL: https://polygonscan.com/

**Comment by Bkroland19** [comment]
Thanks a lot. am done adding that network

**Comment by Bkroland19** [comment]
![Screenshot from 2023-05-16 17-00-24](https://github.com/Ayan-Banerjee-918/VoteBlocks-Dapp/assets/65455750/63c5fbfe-c783-4788-8e60-d54b96549dd9)

**Comment by Bkroland19** [comment]
i still get the same error

**Comment by Ayan-Banerjee-918** [comment]
Check if the acc has already been imported once, because i imported it just now for testing, and its working fine on my end

**Comment by Bkroland19** [comment]
No, it doesn't.

**Comment by Bkroland19** [comment]
cant i configure another address

**Comment by Ayan-Banerjee-918** [comment]
Do you want me to make you administrator? Because its definitely a metamask issue on your end!

Or do you want me to create another admin account, and you would like to give yourself the administrator role using that acc?

**Comment by Bkroland19** [comment]
Yes, you can do that. I want to make my self the admin

**Comment by Ayan-Banerjee-918** [comment]
Okay give me a few minutes!!

**Comment by Bkroland19** [comment]
Okay Sir , i appreciate

**Comment by Ayan-Banerjee-918** [comment]
Try this:

Aadhar : 222222222222
Password : a54GbZevn4068L293abchK8a9r81x>30cQAe0bc842I90Idm]oD54Ka48f3C,$cxWq13be720v
Setup Key : ME4XEOBRPAZTAY2R

Metamask Key: 4c41b78e31d3f464eac7f5b2ac9c8ecae675b05beec66b1d2030376de8b9c0c6

**Comment by Bkroland19** [comment]
the account is  created on metamask but when i navigate to 
admin i get this 
![Uploading Screenshot from 2023-05-16 17-57-28.png…]()

**Comment by Bkroland19** [comment]
account created on metamask  but this link sends 404
https://voteblocks.netlify.app/adminApp/adminLogin

**Comment by Ayan-Banerjee-918** [comment]
Yea first you need to connect the wallet to the site then it will work... Go to metamask , you will see on the top left it says not connected, click on that, it will connect then try.

The 404 is for preventing unauthorized access, so that only the sole administrator who has a unique metamask key can access the page and no one else!

**Comment by Bkroland19** [comment]
yes i have accessed it now let me try the logins u sent me

**Comment by Bkroland19** [comment]
Yes bro it has worked now i need to use the google authenticator where do i
get it from

**Comment by Ayan-Banerjee-918** [comment]
From playstore/appstore, or tbh you can use any authenticator app, just put the secret key into the authenticator and it will work.

**Comment by Bkroland19** [comment]
I have logged successfully but i see a list of other  users  how can i
change this is it the ipfs  ??

**Comment by Bkroland19** [comment]
surely it worked i appreciate may God bless  the works of your hands

**Comment by Ayan-Banerjee-918** [comment]
To do that, you need to compile the contract yourself and host it on a new blockchain, then it wont have other users... You are not supposed to remove other users in this build!

**Comment by Ayan-Banerjee-918** [comment]
Closing the issue!

**Comment by Bkroland19** [comment]
oH thanks so  how do i deploy to that network Sir

**Comment by Bkroland19** [comment]
I wont remove anyone

**Comment by Bkroland19** [comment]
Hello Sir

**Comment by Bkroland19** [comment]
Am trying to do it on the localhost do i need to change the truffle config
file and set it to mumbai test network

**Comment by Bkroland19** [comment]
Hello Mr Ayan , if i want to change it to my settting or if i want to use localhost what should  I do

**Comment by Bkroland19** [comment]
because  when i configure localhost the admin route brings 404

**Comment by Bkroland19** [comment]
Its not working on localhost

**Comment by Ayan-Banerjee-918** [comment]
It's not working because you aren't setting your account ID as admin account in ur localhost....
Look at the contract, you should be able to figure it out yourself....

**Comment by Bkroland19** [comment]
Hi Ayan,

I hope you're doing well. I received your email regarding the issue I'm
facing with my account. I appreciate your guidance so far. However, it
seems that I haven't set my account ID as an admin account in my localhost,
which is causing the problem. I will take a closer look at the contract and
try to figure it out myself.

Thank you for your assistance. If I have any further questions, I'll reach
out to you.

Best regards,
Bukenya Kizza

**Comment by Bkroland19** [comment]
do i have to set it from here    constructor(){
string memory hsh=
"d%4c50e2dbA5&ed&dd90U&2d-R]73d1]Wc73+54u9bKx45672ib26f0p1Nmk_+20cpdC(b5712"
;
address addr=0xCDbD5B3D6347eedbDC0149bF920527D525412D25;
***@***.***",
collisionHash(hsh),'0','MRSDSMCVGJSFENZT',true));
voterList.push(userlist[0]);
UserRole[0]=true;
UserToId[addr]=0;
userExists[addr]=true;
}

**Comment by Bkroland19** [comment]
am confused do i use this contract address or after running truffle migrate
or i use the one in metamask am really new in blockchain      Starting
migrations...
======================
> Network name:    'development'
> Network id:      1684473457994
> Block gas limit: 6721975 (0x6691b7)


1_initial_migration.js
======================

   Deploying 'Voters'
   ------------------
   > transaction hash:
 0x390ca531730b74f8a5a00b9fa0a56153c4f2ffdc526a2b8ba8bb6769fe23c65a
   > Blocks: 0            Seconds: 0
   > contract address:    0x796A0B1345BA885a9E43eCbBc4DA8b411170A43b
   > block number:        1
   > block timestamp:     1684474065
   > account:             0x202e906591B35329513369f15C88971D251b6bBa
   > balance:             99.89442668
   > gas used:            5278666 (0x508bca)
   > gas price:           20 gwei
   > value sent:          0 ETH
   > total cost:          0.10557332 ETH

   > Saving artifacts
   -------------------------------------
   > Total cost:          0.10557332 ETH

Summary
=======
> Total deployments:   1
> Final cost:          0.10557332 ETH

**Comment by Ayan-Banerjee-918** [comment]
You use the address of the account you logged in to metamask with and the one you want as admin account.
