### ISSUE TITLE
Contract

### ISSUE THREAD

**Issue by 1130803** [Ayan-Banerjee-918/VoteBlocks-Dapp#3]
Hi, i am having issues with deploying the contract on a new blockchain. Is there step by step that i can follow or anything specific that must be done?

**Comment by Ayan-Banerjee-918** [comment]
Is there any problem regarding compilation of the contract? Or is your issue regarding deployment procedure only?

**Comment by 1130803** [comment]
How are we supposed to give ourselves admin rights? We managed to upload the contract to our own blockchain, but now we have no users which means there is also no admins. Do we have to admin credentials in the contract itself or is there any other way to do this?

**Comment by Ayan-Banerjee-918** [comment]
Well, if you check the contract, the administrator account is clearly being initialised in the constructor...

**Comment by 1130803** [comment]
True, but we don't have the otp

**Comment by 1130803** [comment]
Another question: do we specifically have to use that account or can we add our own in the constructor?

**Comment by J0K3RSn0w** [comment]
Good evening Ayan,

I had acouple of question regarding the users that is in the smart contract being created when init the smart contract.
1. Do I have to specifically use that specific account or is it possible for me to change it and what are the steps required to do so? (how will I be able to get the otp for this account?)

2. If I am really forced to use the account given in the constructure where can I find the necessary account info to import that account to my Metamask. like provided with the test account details. (Aadid, metamask Import code, otp code, login key)

3. When deploying the smart contract onto my own block chain and creating a user how can I access the admin account in the constructor to be able to login and getting my other user verified & admin role.

This is an awesome dapp you have build! I am just asking regarding these small details that I couldn't find / understand in the instruction provided. 

Regards,
J0K3RSn0w

**Comment by Ayan-Banerjee-918** [comment]
> Another question: do we specifically have to use that account or can we add our own in the constructor?

@1130803 you are free to use your own account!! As for PWD creation, check I have a js file for password generation, use that to get a password...As for OTP secret key, check under 2fa/authenticator.js , there is a function for generating secret key.....Call that function from somewhere passing your acc and password, and you will get a secret key....Once you have them, put all the details in the contract constructor and you are good to go.

**Comment by Ayan-Banerjee-918** [comment]
> Good evening Ayan,
> 
> I had acouple of question regarding the users that is in the smart contract being created when init the smart contract.
> 
> 1. Do I have to specifically use that specific account or is it possible for me to change it and what are the steps required to do so? (how will I be able to get the otp for this account?)
> 2. If I am really forced to use the account given in the constructure where can I find the necessary account info to import that account to my Metamask. like provided with the test account details. (Aadid, metamask Import code, otp code, login key)
> 3. When deploying the smart contract onto my own block chain and creating a user how can I access the admin account in the constructor to be able to login and getting my other user verified & admin role.
> 
> This is an awesome dapp you have build! I am just asking regarding these small details that I couldn't find / understand in the instruction provided.
> 
> Regards, J0K3RSn0w

@J0K3RSn0w 

1. Mentioned in above response.
2. You can use your own account which you create in metamask. Refer to previous response.
3. Same as 1 and 2... Once you can login with your admin account, you are free to do anything you want from the panel itself...Do note  that to access admin panel, first you need to connect the metamask acc to the site , otherwise you might get a 404 error..

**Comment by J0K3RSn0w** [comment]
Thank you for responding so fast! @Ayan-Banerjee-918 

Is it possible to use the registration page to get these information and use the details  in the contract constructor? 

or when redeploying the contract to add the user in the constructor the OTP will not work?
because of the contract address change? 

And if the OTP will not work., how can I either get a new OTP for the user constructor to use to login or make it that the previous OTP works with the redeployed contract?

**Comment by Ayan-Banerjee-918** [comment]
@J0K3RSn0w like I said in my previous response, utilize the appropriate functions to generate password and secret key for your administrator account.....As long as the secret key is generated from your account ID and password, the OTP is bound to work always...

**Comment by J0K3RSn0w** [comment]
Thank you very much @Ayan-Banerjee-918, 

I manage to get admin access with my own blockchain using the contract constructure.
