### ISSUE TITLE
getting admin credentials

### ISSUE THREAD

**Issue by Bkroland19** [Ayan-Banerjee-918/VoteBlocks-Dapp#4]
am i supposed to set the admin address in the constructor ? and am i supposed to make changes in the truffle config if yes kindly send me  your truffle config i want to use  the mumbai test net you used    am still getting 404 when i navigate to the admin page 
![Screenshot from 2023-05-31 16-43-44](https://github.com/Ayan-Banerjee-918/VoteBlocks-Dapp/assets/65455750/6b11b63e-63b8-4173-85bd-14250cb56a78)

**Comment by Ayan-Banerjee-918** [comment]
Yes u need to set it in the constructor. No changes in truffle. And you need to compile the contract and then put it on Mumbai net (Check build setup to see how), then get the contract address and paste in 'client/src/config.js'. After that you need to run the website, connect ur account via metamask client, and then go to the admin page....

If it still doesn't work, it means you aren't doing the steps properly or facing issues regarding contract compilation and putting it on Mumbai testnet....For that I would advise you to check the internet , there are plenty of resources out there with vivid instructions regarding how to do the same..

**Comment by Bkroland19** [comment]
okay sir let me first try out that

**Comment by Bkroland19** [comment]
bro that refused to work out

**Comment by Bkroland19** [comment]
now on the voters part there is an issue when trying to login and trying to verify the otp 
![Screenshot from 2023-06-15 16-57-26](https://github.com/Ayan-Banerjee-918/VoteBlocks-Dapp/assets/65455750/d1b1fcd9-b040-4ea5-84a9-4e23d638998f)

**Comment by Bkroland19** [comment]
kindly help me out i would like to contribute to this and use it as my final year project or can we have a zoom for 20minutes kindly and we solve it

**Comment by Ayan-Banerjee-918** [comment]
Did you setup infura properly ? It's written in readme.md

**Comment by Bkroland19** [comment]
VITE_PROJECT_ID=4d57b583ecb3rwrs34c4fasb0ab093cef390b2
VITE_API_KEY_SECRET=1fd4746ab3sdsc3405c96a0a42fefa4bc959

yes i did like that

**Comment by Ayan-Banerjee-918** [comment]
You are supposed to put the ids within quotes ""

**Comment by Bkroland19** [comment]
okay let me see that

**Comment by Bkroland19** [comment]
the infura error is now out but this remains  
![Screenshot from 2023-06-15 18-41-02](https://github.com/Ayan-Banerjee-918/VoteBlocks-Dapp/assets/65455750/fe320da2-a382-4ddc-bbc2-ab6d8ae8c6b6)

**Comment by Bkroland19** [comment]
it doesnt verify

**Comment by Ayan-Banerjee-918** [comment]
Did you register the account you are trying to login with?

**Comment by Bkroland19** [comment]
yes regitering works perfectly

**Comment by Bkroland19** [comment]
Uncaught (in promise) Error: call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="getUserDetails()", data="0x", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)
    at Logger.makeError (index.ts:269:28)
    at Logger.throwError (index.ts:281:20)
    at Interface.decodeFunctionResult (interface.ts:427:23)
    at Contract.<anonymous> (index.ts:400:44)
    at Generator.next (<anonymous>)
    at fulfilled (_version.ts:1:24)

**Comment by Ayan-Banerjee-918** [comment]
Have you deployed the contract on polygon?

**Comment by Bkroland19** [comment]
how do i do that thats what is limiting me  am failing to set the truffle config from localhost to point to mumbai testnet

**Comment by Bkroland19** [comment]
will this work    truffle migrate --network mumbai

**Comment by Ayan-Banerjee-918** [comment]
Read the polygon docs...You can do it with truffle, but with remix ide it will be easier to deploy:
https://wiki.polygon.technology/docs/category/deploying-contracts

**Comment by Bkroland19** [comment]
okay let first go thru the doc you sent

**Comment by Bkroland19** [comment]
all is failing can we schedule a meeting at your convenient time ?? kindly

**Comment by Ayan-Banerjee-918** [comment]
How did you deploy?

**Comment by Bkroland19** [comment]
using the command  truffle migrate --network mumba

**Comment by Ayan-Banerjee-918** [comment]
I dont think you are following the docs.....I cant help you in this regard!! Read the docs, do according to that...And like I said use remix ide for easier deployment!

**Comment by Bkroland19** [comment]
I have deployed the contract on mumbai testnet 
All other steps are working , registering works but logining in is not preoceeding from that second 2FA  it brings this error 



Error: call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="getUserDetails()", data="0x", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)
    at Logger.makeError (index.ts:269:28)
    at Logger.throwError (index.ts:281:20)
    at Interface.decodeFunctionResult (interface.ts:427:23)
    at Contract.<anonymous> (index.ts:400:44)
    at Generator.next (<anonymous>)
    at fulfilled (_version.ts:1:24)

**Comment by Ayan-Banerjee-918** [comment]
Okay, did you validate the registered user from the admin panel?

**Comment by Bkroland19** [comment]
oh nop i havent validated the user

**Comment by Bkroland19** [comment]
now let me first proceed to the admin panel

**Comment by Ayan-Banerjee-918** [comment]
That shouldn't be the problem because as far as I remember I had setup the system in a manner that invalidated user will be shown as not validated yet!!! But anyways, try to validate from admin panel and then revert back to me..

**Comment by Bkroland19** [comment]
alright let me work on it ASAP

**Comment by Bkroland19** [comment]
![Screenshot from 2023-06-17 16-28-04](https://github.com/Ayan-Banerjee-918/VoteBlocks-Dapp/assets/65455750/f43fc05b-9ddb-4cd2-b582-f4f261006341)






I have connected my metamask account and copied its address and pasted it in the smart contract as the contract address now when i try to navigate to the login page for the admin  i get the 404 error

**Comment by Ayan-Banerjee-918** [comment]
You had setup a contract address in the constructor of the contract to be admin account, did you use that account?

**Comment by Bkroland19** [comment]
its now working 
![Screenshot from 2023-06-17 16-34-37](https://github.com/Ayan-Banerjee-918/VoteBlocks-Dapp/assets/65455750/372f1f69-2573-407e-b676-d8e30c518c48)

**Comment by Bkroland19** [comment]
now how do i register an admin coz whenever i connect my account and navigate to the admin route its telling me that the account is registered that i should proceed to login yet i dont have the adhar id and login key

**Comment by Bkroland19** [comment]
![Uploading Screenshot from 2023-06-17 17-04-28.png…]()

**Comment by Bkroland19** [comment]
![Screenshot from 2023-06-17 17-04-28](https://github.com/Ayan-Banerjee-918/VoteBlocks-Dapp/assets/65455750/61a854b7-f7e8-4c72-93d0-3698fce42050)

**Comment by Bkroland19** [comment]
so does it mean that i cant register an admin

**Comment by Bkroland19** [comment]
and where do i get the login credentials for the admin

**Comment by Ayan-Banerjee-918** [comment]
Are you copy pasting code? I don't think you are understanding how the codebase works!!

Otherwise you wouldnt have asked such a question like where would u get the ID Pass...

You have provided the admin details as part of the constructor in the contract, you have to use them for login....

**Comment by Bkroland19** [comment]
yes thats what i used forsure

**Comment by Bkroland19** [comment]
here is what i have and what i am using to login but the login key isnt there


![Screenshot from 2023-06-18 07-14-18](https://github.com/Ayan-Banerjee-918/VoteBlocks-Dapp/assets/65455750/c63544d1-7b25-4b7e-bd92-6b73ddaca9d3)
![Screenshot from 2023-06-18 07-14-18](https://github.com/Ayan-Banerjee-918/VoteBlocks-Dapp/assets/65455750/711f261f-cf42-45a8-a9fb-7da28ad1a345)

**Comment by Bkroland19** [comment]
![Screenshot from 2023-06-18 07-14-32](https://github.com/Ayan-Banerjee-918/VoteBlocks-Dapp/assets/65455750/10a1944c-d8a4-4e57-ab6f-0f1ec643a726)

**Comment by Bkroland19** [comment]
am confused where to get the admin details from the constuctor only has  the adhar id

**Comment by Ayan-Banerjee-918** [comment]
The hsh is your password

> here is what i have and what i am using to login but the login key isnt there
> 
> ![Screenshot from 2023-06-18 07-14-18](https://user-images.githubusercontent.com/65455750/246643312-c63544d1-7b25-4b7e-bd92-6b73ddaca9d3.png) ![Screenshot from 2023-06-18 07-14-18](https://user-images.githubusercontent.com/65455750/246643317-711f261f-cf42-45a8-a9fb-7da28ad1a345.png)

**Comment by Bkroland19** [comment]
yes i  use the login key as the hsh but on the point of otp  it says invalid otp ??

**Comment by Ayan-Banerjee-918** [comment]
How are you getting the OTP? Which key did you use to setup OTP?

**Comment by Bkroland19** [comment]
this is what i use 
![Screenshot from 2023-06-19 16-48-08](https://github.com/Ayan-Banerjee-918/VoteBlocks-Dapp/assets/65455750/1131a833-93ac-495f-9416-b6357274bd84)

**Comment by Ayan-Banerjee-918** [comment]
Did you generate this key properly? If it does not work, try regenerating the key...
And yes that is the secret key you need to use for the OTP.

**Comment by Bkroland19** [comment]
How can i regenerate the key Kindly

**Comment by Ayan-Banerjee-918** [comment]
How did you generate the key 'MRSDSMCVGJSFENYM' ?

**Comment by Bkroland19** [comment]
it was in your code

**Comment by Ayan-Banerjee-918** [comment]
That is not a random sequence of characters. Its tied to the account. 
If you are the user , the code generates it for you.
If you are the main administrator , you need to generate the key yourself using the code..
Check Register.jsx and authenticate.js to find out how to do so....Its vanilla javascript ...Use it to get the secret key

**Comment by Bkroland19** [comment]
Ok, thanks for the clarification.

**Comment by Bkroland19** [comment]
hello i have managed to login the admin thanks

**Comment by Bkroland19** [comment]
Now let me test all aprts and provide you with feedback

**Comment by Bkroland19** [comment]
Problem well solved thanks @Ayan-Banerjee-918
