### ISSUE TITLE
an inquiry 

### ISSUE THREAD

**Issue by Bkroland19** [Ayan-Banerjee-918/VoteBlocks-Dapp#5]
do i need to setup any sort of database coz   the admin logged in but i cant see the option for verifying users

**Comment by Bkroland19** [comment]
And also starting the vote

**Comment by Ayan-Banerjee-918** [comment]
Which portal did u login to?

**Comment by Bkroland19** [comment]
the admin portal

**Comment by Ayan-Banerjee-918** [comment]
Then everything should come there itself....I am not understanding the issue you are facing ...Show me a screenshot

**Comment by Bkroland19** [comment]
ama gonna send u screenshots

**Comment by Bkroland19** [comment]
what do you pass in as the user and pass in this function  export const auth2fa = (user, pass) => {
	reg2FaAuth(user, pass);
	console.log(qrdata, secKey);
	return [qrdata, secKey];
};
